### ISSUE TITLE
Python scripts are encoded with Windows CRLF line terminators

### ISSUE THREAD

**Issue by clopez** [ddcc/microparse#1]
This makes impossible to run the scripts "directly" on Linux.
With "directly" I mean by executing them as "./script.py" rather than doing "python script.py"

```
$ ./microparse.py 
: No such file or directory

$ file microparse.py 
microparse.py: Python script, ASCII text executable, with CRLF line terminators

$ fromdos microparse.py 

$ file microparse.py 
microparse.py: Python script, ASCII text executable

$ ./microparse.py 
usage: microparse.py [-h] [-c] [-e] [-o OUTPUT] [-p] [-r] [-t {amd,intel,via}]
                     [-v]
                     target
microparse.py: error: the following arguments are required: target
```

I could submit a patch, but it would be a very large patch.. so I guess that maybe you prefer to directly run the fromdos  utility on the scripts and commit yourself the result.

Thanks

**Comment by ddcc** [comment]
Fixed in 0b58a9ba1089ce906048722653783bfe15beed7a
